import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./global/Container";
import Navbar from "./navbar/Navbar";
import AuthProviders from './auth-providers';
import Providers from './providers';
import Footer from "./global/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  preload: true,
  fallback: ['system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: "Licenta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviders>
          <Providers>
            <Navbar />
            <Container>{children}</Container>
            <Footer />
          </Providers>
        </AuthProviders>
      </body>
    </html>
  );
}
